CREATE TABLE `machine` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(256) NOT NULL DEFAULT '' COMMENT '名称',
  `img_url` varchar(256) NOT NULL DEFAULT '' COMMENT '图片地址',
  `currency` enum('GRIN','CKB','ZEC','BTC') NOT NULL DEFAULT 'BTC' COMMENT '所属币种',
  `machine_model` varchar(256) NOT NULL DEFAULT '' COMMENT '矿机型号',
  `machine_power` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '矿机功率',
  `machine_consume_power` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '矿机功耗',
  `unit` int(11) NOT NULL DEFAULT '0' COMMENT '算力单位',
  `uint_level` varchar(128) NOT NULL DEFAULT '' COMMENT '算力单位的单位',
  `daily_output` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '日产值',
  `daily_electricity_fee` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '日电费',
  `daily_income` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '日净收益',
  `introduce` text NOT NULL COMMENT '介绍',
  `status` enum('OPEN','CLOSE') NOT NULL DEFAULT 'OPEN',
  `create_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '添加时间',
  `update_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='矿机表';

INSERT INTO `spm-test`.`machine` (`id`, `name`, `img_url`, `currency`, `machine_model`, `machine_power`, `machine_consume_power`, `machine_consume_power_unit`, `unit`, `uint_level`, `daily_output`, `daily_electricity_fee`, `daily_income`, `introduce`, `status`, `create_time`, `update_time`) VALUES ('1', '蚂蚁 T17+', '', 'BTC', '蚂蚁 T17+', '44.00', '2820.00', 'W/T', '64', 'TH/s', '36.37', '21.66', '14.28', '<p>购买前请认真阅读如下说明，提交订单即视为您已充分理解并完全同意以下内容：</p>\r\n                    <p>1.用户下单即代表同意全权委托挖易代为购买该型号的矿机并代为处理相关的运输和托管事宜；</p>\r\n                    <p>2.本产品每个账户限购2台；</p>\r\n                    <p>3.发货时间：2020.05.11-2020.07.01；</p>\r\n                    <p>4.本产品支持顺丰（默认空运）、顺丰特惠、德邦物流、德邦快递、圆通快递配送，具体费用请咨询物流服务供应商；</p>\r\n                    <p>5.请点击查看运输保险的主要条款，一旦发生保险事故，经您请求，我们将代为向保险公司索赔，如因您未能提交真实、准确、完整的资料导致保险公司拒绝赔付全部或部分款项，您自行承担责任。 </p>\r\n                    <p>注意：因各个国家和地区电源插头不一样，电源不包含220V端电源线。 想了解更多细节或者订购更多数量，请通过蚂蚁售前服务公众号联系我们。</p>', 'OPEN', '2020-07-02 12:00:00', '2020-07-02 12:00:00');
INSERT INTO `spm-test`.`machine` (`id`, `name`, `img_url`, `currency`, `machine_model`, `machine_power`, `machine_consume_power`, `machine_consume_power_unit`, `unit`, `uint_level`, `daily_output`, `daily_electricity_fee`, `daily_income`, `introduce`, `status`, `create_time`, `update_time`) VALUES ('2', '神马 M20S', '', 'BTC', '神马 M20S', '48.00', '3360.00', 'W/T', '70', 'TH/s', '39.78', '25.80', '13.46', '<p>购买前请认真阅读如下说明，提交订单即视为您已充分理解并完全同意以下内容：</p>\r\n                    <p>1.用户下单即代表同意全权委托挖易代为购买该型号的矿机并代为处理相关的运输和托管事宜；</p>\r\n                    <p>2.本产品每个账户限购2台；</p>\r\n                    <p>3.发货时间：2020.05.11-2020.07.01；</p>\r\n                    <p>4.本产品支持顺丰（默认空运）、顺丰特惠、德邦物流、德邦快递、圆通快递配送，具体费用请咨询物流服务供应商；</p>\r\n                    <p>5.请点击查看运输保险的主要条款，一旦发生保险事故，经您请求，我们将代为向保险公司索赔，如因您未能提交真实、准确、完整的资料导致保险公司拒绝赔付全部或部分款项，您自行承担责任。 </p>\r\n                    <p>注意：因各个国家和地区电源插头不一样，电源不包含220V端电源线。 想了解更多细节或者订购更多数量，请通过蚂蚁售前服务公众号联系我们。</p>', 'OPEN', '2020-07-02 12:00:00', '2020-07-02 12:00:00');
INSERT INTO `spm-test`.`machine` (`id`, `name`, `img_url`, `currency`, `machine_model`, `machine_power`, `machine_consume_power`, `machine_consume_power_unit`, `unit`, `uint_level`, `daily_output`, `daily_electricity_fee`, `daily_income`, `introduce`, `status`, `create_time`, `update_time`) VALUES ('3', '蚂蚁 Z15', '', 'ZEC', '蚂蚁 Z15', '3.60', '1510.00', 'W/K', '420', 'K', '165.60', '12.68', '152.67', '<p>购买前请认真阅读如下说明，提交订单即视为您已充分理解并完全同意以下内容：</p>\r\n                    <p>1.用户下单即代表同意全权委托挖易代为购买该型号的矿机并代为处理相关的运输和托管事宜；</p>\r\n                    <p>2.本产品每个账户限购2台；</p>\r\n                    <p>3.发货时间：2020.05.11-2020.07.01；</p>\r\n                    <p>4.本产品支持顺丰（默认空运）、顺丰特惠、德邦物流、德邦快递、圆通快递配送，具体费用请咨询物流服务供应商；</p>\r\n                    <p>5.请点击查看运输保险的主要条款，一旦发生保险事故，经您请求，我们将代为向保险公司索赔，如因您未能提交真实、准确、完整的资料导致保险公司拒绝赔付全部或部分款项，您自行承担责任。 </p>\r\n                    <p>注意：因各个国家和地区电源插头不一样，电源不包含220V端电源线。 想了解更多细节或者订购更多数量，请通过蚂蚁售前服务公众号联系我们。</p>', 'OPEN', '2020-07-02 12:00:00', '2020-07-02 12:00:00');
INSERT INTO `spm-test`.`machine` (`id`, `name`, `img_url`, `currency`, `machine_model`, `machine_power`, `machine_consume_power`, `machine_consume_power_unit`, `unit`, `uint_level`, `daily_output`, `daily_electricity_fee`, `daily_income`, `introduce`, `status`, `create_time`, `update_time`) VALUES ('4', 'Toddminer C1 Pro', '', 'CKB', 'Toddminer C1 Pro', '900.00', '2700.00', 'W/T', '3', 'TH/s', '95.78', '22.68', '72.65', '<p>购买前请认真阅读如下说明，提交订单即视为您已充分理解并完全同意以下内容：</p>\r\n                    <p>1.用户下单即代表同意全权委托挖易代为购买该型号的矿机并代为处理相关的运输和托管事宜；</p>\r\n                    <p>2.本产品每个账户限购2台；</p>\r\n                    <p>3.发货时间：2020.05.11-2020.07.01；</p>\r\n                    <p>4.本产品支持顺丰（默认空运）、顺丰特惠、德邦物流、德邦快递、圆通快递配送，具体费用请咨询物流服务供应商；</p>\r\n                    <p>5.请点击查看运输保险的主要条款，一旦发生保险事故，经您请求，我们将代为向保险公司索赔，如因您未能提交真实、准确、完整的资料导致保险公司拒绝赔付全部或部分款项，您自行承担责任。 </p>\r\n                    <p>注意：因各个国家和地区电源插头不一样，电源不包含220V端电源线。 想了解更多细节或者订购更多数量，请通过蚂蚁售前服务公众号联系我们。</p>', 'OPEN', '2020-07-02 12:00:00', '2020-07-02 12:00:00');
