CREATE TABLE `order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `order_no` varchar(128) NOT NULL DEFAULT '' COMMENT '订单号',
  `team_id` int(11) NOT NULL DEFAULT '0' COMMENT '团id',
  `user_id` varchar(128) NOT NULL DEFAULT '' COMMENT '用户id',
  `machine_id` int(11) NOT NULL DEFAULT '0' COMMENT '矿机id',
  `machine_num` int(11) NOT NULL DEFAULT '0' COMMENT '矿机数量',
  `machine_price` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '矿机单价',
  `machine_total_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '矿机总费用',
  `deposit` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '押金',
  `other_fee` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '其他费用',
  `amount` decimal(15,8) NOT NULL DEFAULT '0.00000000' COMMENT '总金额',
  `usdt_amount` decimal(15,8) NOT NULL DEFAULT '0.00000000' COMMENT 'usdt总金额',
  `cny_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '人民币总金额',
  `usdt_rate` decimal(15,8) NOT NULL DEFAULT '0.00000000' COMMENT '支付币种兑换成USDT的汇率',
  `pay_type` enum('VIRTUAL','ALIPAY','WECHAT') NOT NULL COMMENT '支付方式',
  `currency` enum('USDT','CNY') NOT NULL COMMENT '支付币种',
  `protocol` enum('ERC20') NOT NULL COMMENT '协议',
  `pay_status` enum('REFUND_FAIL','REFUND_SUCCESS','REFUND_WAIT','FAIL','SUCCESS','BEING','TIMEOUT','WAIT') NOT NULL DEFAULT 'WAIT' COMMENT '支付状态',
  `status` enum('FAIL','SUCCESS','BEING') NOT NULL DEFAULT 'BEING' COMMENT '状态',
  `pay_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '支付时间',
  `refund_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '退款时间',
  `create_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '添加时间',
  `update_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单表';