CREATE TABLE `order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `order_no` varchar(128) NOT NULL DEFAULT '' COMMENT '订单号',
  `team_id` int(11) NOT NULL DEFAULT 0 COMMENT '团id',
  `team_machine_id` int(11) NOT NULL DEFAULT 0 COMMENT '团矿机id',
  `user_id` varchar(128) NOT NULL DEFAULT '' COMMENT '用户id',
  `machine_id` int(11) NOT NULL DEFAULT 0 COMMENT '矿机id',
  `machine_num` int(11) NOT NULL DEFAULT 0 COMMENT '矿机数量',
  `machine_price` decimal(15,2) NOT NULL DEFAULT 0.00 COMMENT '矿机单价（售价）',
  `machine_total_amount` decimal(15,2) NOT NULL DEFAULT 0.00 COMMENT '矿机总费用',
  `deposit_simple` decimal(15,2) NOT NULL DEFAULT 0.00 COMMENT '单份押金',
  `deposit` decimal(15,2) NOT NULL DEFAULT 0.00 COMMENT '押金',
  `other_fee_simple` decimal(15,2) NOT NULL DEFAULT 0.00 COMMENT '单份其他费用',
  `other_fee` decimal(15,2) NOT NULL DEFAULT 0.00 COMMENT '其他费用',
  `amount` decimal(15,8) NOT NULL DEFAULT 0.00000000 COMMENT '总金额',
  `usdt_amount` decimal(15,8) NOT NULL DEFAULT 0.00000000 COMMENT 'usdt总金额',
  `usd_amount` decimal(15,2) NOT NULL DEFAULT 0.00 COMMENT '美元总金额',
  `usdt_rate` decimal(15,8) NOT NULL DEFAULT 0.00000000 COMMENT 'USDT兑换成美元的汇率',
  `pay_type` enum('','VIRTUAL','ALIPAY','BANK','WECHAT') NOT NULL DEFAULT '' COMMENT '支付方式',
  `currency` enum('','USDT','USD','CNY') NOT NULL DEFAULT '' COMMENT '支付币种',
  `protocol` enum('','ERC20') NOT NULL DEFAULT '' COMMENT '协议',
  `pay_status` enum('FAIL','SUCCESS','BEING','TIMEOUT','WAIT') NOT NULL DEFAULT 'WAIT' COMMENT '支付状态',
  `refund_amount` decimal(15,8) NOT NULL DEFAULT 0.00000000 COMMENT '退款金额',
  `refund_currency` enum('','USDT','USD','CNY') NOT NULL DEFAULT '' COMMENT '退款币种',
  `refund_protocol` enum('','ERC20') NOT NULL COMMENT '退款的币种协议',
  `refund_type` enum('','VIRTUAL','ALIPAY','BANK','WECHAT') NOT NULL DEFAULT '' COMMENT '退款方式',
  `refund_status` enum('','FAIL','SUCCESS','BEING','WAIT') NOT NULL DEFAULT '' COMMENT '退款状态',
  `status` enum('FAIL','SUCCESS','BEING') NOT NULL DEFAULT 'BEING' COMMENT '状态',
  `pay_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '支付时间',
  `refund_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '退款时间',
  `pay_flow` varchar(4096) NOT NULL DEFAULT '' COMMENT '支付流水',
  `refund_flow` varchar(4096) NOT NULL DEFAULT '' COMMENT '退款流水',
  `pay_usdt_amount` decimal(15,8) NOT NULL DEFAULT 0.00000000 COMMENT '用户支付usdt金额（包括预存账单）',
  `pay_usd_amount` decimal(15,2) NOT NULL DEFAULT 0.00 COMMENT '用户支付usd金额（包括预存账单）',
  `pay_amount` decimal(15,8) NOT NULL DEFAULT 0.00000000 COMMENT '实际支付金额',
  `electricity_order_store_id` int(11) NOT NULL DEFAULT 0 COMMENT '预存电费单id',
  `remarks` varchar(1024) NOT NULL DEFAULT '' COMMENT '备注',
  `has_request_pay` enum('NO','YES') NOT NULL DEFAULT 'NO' COMMENT '是否有请求支付',
  `create_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '添加时间',
  `update_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单表';

