CREATE TABLE `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` char(60) NOT NULL DEFAULT '' COMMENT '用户id',
  `username` varchar(50) NOT NULL DEFAULT '' COMMENT '用户名',
  `password` varchar(60) NOT NULL DEFAULT '' COMMENT '密码',
  `phone` varchar(20) NOT NULL DEFAULT '0' COMMENT '手机号',
  `email` varchar(100) NOT NULL DEFAULT '' COMMENT '邮箱',
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '状态 1正常2异常',
  `create_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '创建时间',
  `creator` varchar(50) NOT NULL DEFAULT '' COMMENT '创建人',
  `edit_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '修改时间',
  `edit_or` varchar(50) NOT NULL DEFAULT '' COMMENT '修改人',
  `source` tinyint(4) NOT NULL DEFAULT '1' COMMENT '注册来源 1web注册2活动注册',
  `reg_ip` varchar(20) NOT NULL DEFAULT '' COMMENT '注册ip',
  `invite_id` varchar(60) NOT NULL DEFAULT '' COMMENT '邀请人id',
  `lang_code` varchar(20) NOT NULL DEFAULT 'en' COMMENT '注册语言',
  `site` tinyint(4) NOT NULL DEFAULT '0' COMMENT '站点信息（详见站点服务）',
  `up_invite_id` char(60) DEFAULT '' COMMENT '上一个邀请人id',
  `user_level` int(11) NOT NULL DEFAULT '1' COMMENT '会员等级',
  `invite_code` varchar(12) DEFAULT '' COMMENT '邀请码',
  `country` varchar(100) NOT NULL DEFAULT '' COMMENT '国家',
  `area_code` varchar(100) NOT NULL DEFAULT '' COMMENT '区号',
  `reg_platform` tinyint(4) NOT NULL DEFAULT '1' COMMENT '注册平台，详细看配置model',
  `is_new` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否是2.0新注册的用户,可享受的活动标识',
  `password_uptime` datetime NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '密码修改时间',
  PRIMARY KEY (`id`),
  KEY `invite` (`invite_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表';