CREATE TABLE `order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` varchar(64) NOT NULL DEFAULT '' COMMENT '用户id',
  `order_sn` varchar(64) NOT NULL DEFAULT '' COMMENT '订单编号',
  `pool_id` int(11) NOT NULL DEFAULT '0' COMMENT '算力池id',
  `pool_name_en` varchar(256) NOT NULL DEFAULT '' COMMENT '算力池名称（英文）',
  `pool_name_zhCn` varchar(256) NOT NULL DEFAULT '' COMMENT '算力池名称（中文）',
  `machine_power` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '矿机功率',
  `management_fee_rate` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '管理费利率',
  `electricity_price` decimal(15,4) NOT NULL DEFAULT '0.0000' COMMENT '电费单价',
  `power_unit` decimal(15,4) NOT NULL DEFAULT '0.0000' COMMENT '算力单位',
  `consume_currency` enum('ETH') NOT NULL DEFAULT 'ETH' COMMENT '消耗币种名称',
  `consume` decimal(15,4) NOT NULL DEFAULT '0.0000' COMMENT '消耗币种数量',
  `order_date` date NOT NULL DEFAULT '0000-00-00' COMMENT '订单日期',
  `mine_revenue_daily` decimal(15,8) NOT NULL DEFAULT '0.00000000' COMMENT '每日挖矿收益',
  `pay_status` enum('UNPAID','SUCCESS','FAIL') NOT NULL DEFAULT 'UNPAID' COMMENT '支付状态',
  `income_status` enum('INACTIVE','ACTIVE') NOT NULL DEFAULT 'INACTIVE' COMMENT '收益状态',
  `exchange_rate` decimal(15,8) NOT NULL DEFAULT '0.00000000' COMMENT '汇率（收益币对udt的汇率）',
  `income_currency` enum('BTC') NOT NULL DEFAULT 'BTC' COMMENT '收益币种名称',
  `income` decimal(15,8) NOT NULL DEFAULT '0.00000000' COMMENT '收益（btc）',
  `income_usd` decimal(15,4) NOT NULL DEFAULT '0.0000' COMMENT '收益（美元）',
  `create_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '添加时间',
  `update_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单表';